language: python

python:
  - "3.7"
  - "3.8"
  - "3.9"

install:
  - pip install flake8
  - python setup.py install

script:
  - flake8 qweechat
  - qweechat-testproto --version
  - qweechat-testproto --help
